name: bunker
description: Bunker card game app companion

publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"

dependencies:
  flutter:
    sdk: flutter
  kplayer: ^0.1.11
  animations: ^2.0.1
  camera: ^0.9.2+1
  image: ^3.0.2
  qr_code_dart_scan: ^0.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/text/

